vice coordinator:
  id: 2
  name: Vice Chair

project coordinator:
  id: 3
  name: Meeting Chair

student:
  id: 4
  name: Student

postdoc:
  id: 5
  name: Postdoc

technician:
  id: 7
  name: Technician

phd_student:
  id: 8
  name: PhD Student